### ISSUE TITLE
nixpkgs pinning script is broken as of Nix 2.0

### ISSUE THREAD

**Issue by taktoa** [thoughtpolice/clash-playground#2]
There is an updated version of `fetchnix.nix` [here](https://nixos.wiki/wiki/How_to_fetch_Nixpkgs_with_an_empty_NIX_PATH) that describes a version that will properly work with Nix 2.0 (at the cost of requiring two hashes in `nixpkgs.json`).

**Comment by thoughtpolice** [comment]
I'd rather just make Nix 2.0 mandatory, TBQH.

**Comment by thoughtpolice** [comment]
Fixed in HEAD.
